#!/bin/sh

ENV=${1}

if [ "${ENV}" == "prod" ]; then
  curl -XPOST "https://deploy.strange-orbit.com/api/stacks/webhooks/212f2146-01d5-4354-9b4e-4dccf349cf52"
fi
if [ "${ENV}" == "stage" ]; then
  curl -XPOST "https://deploy.strange-orbit.com/api/stacks/webhooks/df77c962-c0fa-4073-aa11-38603127791c"
fi
