#!/bin/sh

ENV=${1}

if [ "${ENV}" == "prod" ]; then
  curl -XPOST "https://deploy.strange-orbit.com/api/stacks/webhooks/d2347624-d4ca-4a1d-820f-ac6010895522"
fi
if [ "${ENV}" == "stage" ]; then
  curl -XPOST "https://deploy.strange-orbit.com/api/stacks/webhooks/126f7487-1eec-4eac-8b08-ff9cc64a2ea5"
fi
